
INSERT INTO
  med_img.Patient(given_name, family_name, email, address, sex, birthdate)
VALUES
('Virginia','Macejkovic','Marley73@yahoo.com','{"country": "Mauritius", "state": "Minnesota", "city": "East Orion"}',9,'1965-08-04'),
('Syble','Parisian','Everardo.Stark@hotmail.com','{"country": "Kyrgyz Republic", "state": "Rhode Island", "city": "Toyfort"}',9,'1973-09-03'),
('Juwan','Mante','Jakayla.Reichert@hotmail.com','{"country": "Morocco", "state": "Colorado", "city": "East ;Josianeside"}',2,'1965-09-23'),
('Jaclyn','Pacocha','Pietro_Stark@hotmail.com','{"country": "Japan", "state": "Delaware", "city": "Tellymouth"}',2,'1972-04-30'),
('Kiera','Keeling','Connie.Hansen97@yahoo.com','{"country": "Niger", "state": "Minnesota", "city": "South Freeman"}',9,'1998-09-21'),
('Woodrow','Becker','Myrtice70@gmail.com','{"country": "Thailand", "state": "Indiana", "city": "Port Vanview"}',9,'1997-12-30'),
('Tiara','Wisoky','Natalie.OHara23@yahoo.com','{"country": "Iraq", "state": "Massachusetts", "city": "West Virgil"}',0,'1977-07-03'),
('Helena','Kertzmann','Harold28@gmail.com','{"country": "Iran", "state": "Connecticut", "city": "East Mabel"}',2,'1977-10-18'),
('Mylene','Buckridge','Armand92@gmail.com','{"country": "Pakistan", "state": "Delaware", "city": "Trompchester"}',2,'1996-02-21'),
('Claude','Hirthe','Hoyt.Zulauf53@hotmail.com','{"country": "Marshall Islands", "state": "South Dakota", "city": "Lake Eulahchester"}',2,'1962-01-29'),
('Rhoda','MacGyver','Allison.Vandervort@gmail.com','{"country": "Montenegro", "state": "Oklahoma", "city": "South Londonshire"}',1,'1980-10-24'),
('Tomas','Von','Margaret.Koch43@yahoo.com','{"country": "Paraguay", "state": "Oklahoma", "city": "Medhurstborough"}',1,'1961-08-13'),
('Toney','Ziemann','Angelo_Bradtke98@hotmail.com','{"country": "Puerto Rico", "state": "Massachusetts", "city": "Lake Alvis"}',9,'1989-08-03'),
('Kaelyn','Eichmann','Fanny.Nicolas94@gmail.com','{"country": "Kazakhstan", "state": "Alabama", "city": "Carletontown"}',1,'1977-07-20'),
('Vidal','Casper','Lori.Casper36@yahoo.com','{"country": "Algeria", "state": "South Dakota", "city": "Port Jayda"}',2,'1988-05-27'),
('Giles','Feeney','Trudie70@yahoo.com','{"country": "Sierra Leone", "state": "Indiana", "city": "West Larry"}',1,'1985-05-03'),
('Amparo','Nolan','Wanda_Fritsch83@gmail.com','{"country": "Tunisia", "state": "Vermont", "city": "Joanieside"}',9,'1971-09-10'),
('Sydni','West','Kolby39@yahoo.com','{"country": "Vietnam", "state": "Rhode Island", "city": "McCulloughberg"}',0,'1960-01-15'),
('Hassan','Kuhic','Yvonne.Fay93@hotmail.com','{"country": "Zambia", "state": "Minnesota", "city": "South Santamouth"}',2,'1990-01-20'),
('Korbin','Schroeder','Laverne_Russel15@gmail.com','{"country": "Kuwait", "state": "California", "city": "Casimermouth"}',1,'1965-11-22'),
('Lizzie','Pfeffer','Jacynthe.Schmidt42@yahoo.com','{"country": "Jamaica", "state": "Maryland", "city": "Daleland"}',2,'1990-11-11'),
('Jared','Pacocha','Lura_Mills38@gmail.com','{"country": "Ireland", "state": "Colorado", "city": "Edisonmouth"}',2,'1968-12-28'),
('Zane','Will','Liliane95@yahoo.com','{"country": "Philippines", "state": "Montana", "city": "West Jaymebury"}',2,'1976-04-09'),
('Bryana','Douglas','Bria.Gutkowski@yahoo.com','{"country": "Liberia", "state": "Oklahoma","city": "Hoppefort"}',2,'1966-05-31'),
('Donald','Stark','Clement_Waters36@yahoo.com','{"country": "Zambia", "state": "Montana", "city": "Rogahnchester"}',9,'1968-09-21'),
('Antone','Cummerata','Maribel.Klocko18@yahoo.com','{"country": "Switzerland", "state": "Alaska", "city": "Quintenfurt"}',9,'1990-04-26'),
('Garry','Toy','Whitney.Spinka99@yahoo.com','{"country": "Turkmenistan", "state": "Rhode Island", "city": "Rubyeburgh"}',1,'1987-10-19'),
('Elmira','Franecki','Arno.Grimes@gmail.com','{"country": "Djibouti", "state": "Nebraska", "city": "New Lilianshire"}',9,'1998-04-20'),
('Kimberly','Willms','Neal.Marvin1@hotmail.com','{"country": "Algeria", "state": "Iowa", "city": "Port Trevor"}',9,'1979-09-19'),
('Nelson','Barrows','Jerry78@hotmail.com','{"country": "Indonesia", "state": "Wyoming", "city": "Durganland"}',0,'1996-12-24'),
('Aubrey','Hilll','Keanu.Lebsack@hotmail.com','{"country": "Lebanon", "state": "New Jersey", "city": "South Samland"}',1,'1992-05-19'),
('Felipa','Dietrich','Dena9@yahoo.com','{"country": "Costa Rica", "state": "Rhode Island", "city": "Port Rebeca"}',9,'1994-07-13'),
('Concepcion','Terry','Benjamin_Casper@yahoo.com','{"country": "Nicaragua", "state": "New Hampshire", "city": "Valentinefort"}',1,'1982-07-27'),
('Raymundo','Brekke','Albertha90@gmail.com','{"country": "Malta", "state": "Nebraska", "city": "Stanberg"}',2,'1990-06-19'),
('Emilio','Koch','Joy.Hilll@yahoo.com','{"country": "Cayman Islands", "state": "Montana", "city": "New Novella"}',0,'1981-04-10'),
('Manuela','Koch','Dereck_Ebert@yahoo.com','{"country": "Oman", "state": "New Mexico", "city": "South Stanford"}',1,'1965-03-27'),
('Antonetta','Strosin','Fatima.Kertzmann55@yahoo.com','{"country": "Cayman Islands", "state": "North Dakota", "city": "Towneville"}',2,'1993-10-19'),
('Princess','Keeling','Finn_Muller38@hotmail.com','{"country": "Moldova", "state": "Oklahoma", "city": "Kassulketown"}',1,'1989-02-15'),
('Jordi','Eichmann','Phoebe48@hotmail.com','{"country": "Tanzania", "state": "North Carolina", "city": "Bashirianborough"}',9,'1986-03-13'),
('Davion','Nitzsche','Lina.Wisozk@gmail.com','{"country": "Kiribati", "state": "Wisconsin","city": "East Veda"}',2,'1995-10-29'),
('Issac','Walker','Brando.Parisian56@hotmail.com','{"country": "Virgin Islands, British", "state": "Colorado", "city": "South Addisonburgh"}',2,'1976-12-13'),
('Emely','Barton','Devon82@gmail.com','{"country": "Saint Pierre and Miquelon", "state": "Idaho", "city": "Parkermouth"}',0,'1999-01-09'),
('Nicholaus','Sauer','Gregg_Walker23@yahoo.com','{"country": "Slovakia (Slovak Republic)", "state": "Montana", "city": "Lake Lula"}',9,'1974-11-07'),
('Nasir','Eichmann','Reece.Gottlieb99@gmail.com','{"country": "Panama", "state": "South Carolina", "city": "Vincenzaton"}',2,'1993-11-08'),
('Keith','Murphy','Rossie69@yahoo.com','{"country": "Kazakhstan", "state": "Arizona", "city": "Mossietown"}',1,'1991-04-19'),
('Vernon','Hane','Anthony.Mann@hotmail.com','{"country": "Bermuda", "state": "Vermont", "city": "Cooperview"}',2,'1999-12-12'),
('Felicia','D''Amore','Aubree21@hotmail.com','{"country": "Swaziland", "state": "Michigan", "city": "Kerlukeshire"}',0,'1981-12-16'),
('Johathan','Romaguera','Brenda55@gmail.com','{"country": "Yemen", "state": "New Hampshire", "city": "Hesselton"}',0,'1975-08-04'),
('Vern','Rosenbaum','Gaston_Ferry@hotmail.com','{"country": "Tonga", "state": "Colorado", "city": "Adriennetown"}',9,'1996-04-26'),
('Mozell','Sauer','Jessika60@hotmail.com','{"country": "Switzerland", "state": "New Hampshire", "city": "Madisonton"}',2,'1987-09-11'),
('Maud','Wolf','Aletha_Adams90@yahoo.com','{"country": "Moldova", "state": "Utah", "city": "Wadeport"}',0,'1983-08-18'),
('Emmitt','Gerhold','Jennie80@hotmail.com','{"country": "Guinea", "state": "Wisconsin", "city": "Jedediahmouth"}',0,'1999-12-05'),
('Lance','Schulist','Monica_Bailey@hotmail.com','{"country": "Denmark", "state": "Oregon", "city": "Kingport"}',2,'1971-12-30'),
('Hanna','Towne','Dorian_McCullough31@hotmail.com','{"country": "Solomon Islands", "state":"Alabama", "city": "West Moseside"}',0,'1967-04-19'),
('Jamaal','Konopelski','Jovani63@hotmail.com','{"country": "Somalia", "state": "New York", "city": "Orntown"}',9,'1970-05-12'),
('Anais','Kemmer','Kurt_Schumm@gmail.com','{"country": "Malaysia", "state": "Utah", "city":"East Destinee"}',0,'1984-06-21'),
('Marguerite','Barton','Declan.OConner@gmail.com','{"country": "Nauru", "state": "Massachusetts", "city": "Wisokystad"}',1,'1997-05-30'),
('Jedediah','Mann','Dennis3@yahoo.com','{"country": "Ireland", "state": "North Carolina", "city": "West Isabellaside"}',1,'1983-06-03'),
('Darion','Orn','Ettie70@yahoo.com','{"country": "Cocos (Keeling) Islands", "state": "Kansas", "city": "Port Willy"}',2,'1966-01-21'),
('Shyann','Hintz','Haskell_Powlowski@yahoo.com','{"country": "Sierra Leone", "state": "Missouri", "city": "South Bryonport"}',9,'1971-07-11'),
('Wendell','Marvin','Angie32@yahoo.com','{"country": "Georgia", "state": "Pennsylvania", "city": "Framichester"}',2,'1969-01-16'),
('Abdiel','Gaylord','Jany50@yahoo.com','{"country": "Papua New Guinea", "state": "Washington", "city": "Quincyton"}',9,'1982-08-06'),
('Bruce','Crooks','Marquise.Renner@gmail.com','{"country": "Spain", "state": "Michigan", "city": "East Brookburgh"}',9,'1965-05-21'),
('Jody','Cremin','Aglae.Kiehn91@yahoo.com','{"country": "Sudan", "state": "Hawaii", "city":"West Isaias"}',0,'1976-10-08'),
('Scarlett','McDermott','Caterina_Abernathy32@yahoo.com','{"country": "Costa Rica", "state": "New York", "city": "New Ernestview"}',0,'1984-08-12'),
('Allan','Stokes','Clementine_Graham51@gmail.com','{"country": "Costa Rica", "state": "Texas", "city": "Port Gracechester"}',2,'1976-03-10'),
('Luna','McLaughlin','Mariana.Hoeger59@yahoo.com','{"country": "Vanuatu", "state": "Montana", "city": "Torpberg"}',9,'1976-02-15'),
('Kaley','Bechtelar','Ervin_Blick@hotmail.com','{"country": "Costa Rica", "state": "South Dakota", "city": "New Adolfhaven"}',0,'1965-02-23'),
('Antwan','Casper','Lula.Greenholt22@gmail.com','{"country": "Luxembourg", "state": "New Jersey", "city": "Howebury"}',0,'1968-06-28'),
('Irma','Barrows','Cecile_Boyer@yahoo.com','{"country": "Northern Mariana Islands", "state": "Idaho", "city": "West Clintonstad"}',0,'1969-05-13'),
('Merritt','Stehr','Hector_Hodkiewicz@yahoo.com','{"country": "Sierra Leone", "state": "Maine", "city": "Bergstromland"}',2,'1967-11-03'),
('Leonora','Swift','Araceli10@yahoo.com','{"country": "New Caledonia", "state": "Texas", "city": "East Bettye"}',1,'1986-11-06'),
('Barton','Batz','Maeve_Williamson@yahoo.com','{"country": "Costa Rica", "state": "Kansas","city": "Port Georgianamouth"}',1,'1990-03-02'),
('Haskell','Spencer','Reuben_Tromp62@yahoo.com','{"country": "Saint Pierre and Miquelon", "state": "Arkansas", "city": "Jackieside"}',2,'1987-08-23'),
('Chloe','Windler','Gladyce68@gmail.com','{"country": "France", "state": "Mississippi", "city": "West Columbusfurt"}',9,'1985-03-28'),
('Ted','VonRueden','Donna.Harber51@gmail.com','{"country": "Guinea", "state": "Arizona", "city": "Flatleyville"}',1,'1979-07-27'),
('Mortimer','Rempel','Pearl_Mayer59@gmail.com','{"country": "Saint Pierre and Miquelon", "state": "Florida", "city": "Ryanfort"}',0,'1965-09-26'),
('Gladyce','Reynolds','Rhianna_McCullough@gmail.com','{"country": "Costa Rica", "state": "New Hampshire", "city": "South Dudley"}',0,'1988-12-29'),
('Tomas','Cassin','Antonetta95@yahoo.com','{"country": "Barbados", "state": "Kentucky", "city": "Kimberlyside"}',1,'1989-02-12'),
('Travis','Stehr','Ransom_Legros@yahoo.com','{"country": "Syrian Arab Republic", "state": "New York", "city": "South Maverick"}',1,'1987-02-15'),
('Dean','Gutkowski','Lavinia.Hermann30@hotmail.com','{"country": "Ireland", "state": "Maine", "city": "East Maryville"}',1,'1975-10-19'),
('Claudie','Romaguera','Heather57@gmail.com','{"country": "Liberia", "state": "Kansas", "city": "Port Joana"}',1,'1981-08-15'),
('Tre','Macejkovic','Alvis38@gmail.com','{"country": "Austria", "state": "Oklahoma", "city": "Blickfort"}',9,'1985-01-29'),
('Wilma','Johnston','Chauncey76@hotmail.com','{"country": "Netherlands Antilles", "state": "Wisconsin", "city": "Bahringerview"}',2,'1963-07-13'),
('Hellen','Toy','Celestine54@hotmail.com','{"country": "Martinique", "state": "New Hampshire", "city": "Bellaside"}',1,'1996-11-26'),
('Lois','Kassulke','Genesis.Reilly@yahoo.com','{"country": "Trinidad and Tobago", "state": "New Jersey", "city": "Dasiaburgh"}',9,'1998-08-19'),
('Matilde','Jerde','Brandon64@yahoo.com','{"country": "Nigeria", "state": "Illinois", "city": "North Lorishire"}',9,'1974-06-20'),
('Terrell','Becker','Katelynn_Homenick93@hotmail.com','{"country": "Virgin Islands, British", "state": "Idaho", "city": "Reillyborough"}',9,'1962-03-06'),
('Jessie','Block','Adell_Beatty7@yahoo.com','{"country": "Algeria", "state": "Delaware", "city": "Lake Candelario"}',9,'1994-08-11'),
('Myrna','Ziemann','Lonzo47@yahoo.com','{"country": "Switzerland", "state": "Nebraska", "city": "Lake Dinatown"}',9,'1997-03-25'),
('Isac','Grant','Hosea98@hotmail.com','{"country": "Timor-Leste", "state": "Missouri", "city": "Simland"}',1,'1965-08-12'),
('Rafaela','Vandervort','Maggie.Mraz91@hotmail.com','{"country": "Guyana", "state": "Wyoming", "city": "Cummingsborough"}',2,'1985-11-22'),
('Justina','Hodkiewicz','Salvatore_Osinski@hotmail.com','{"country": "Costa Rica", "state": "Wisconsin", "city": "Biankashire"}',1,'1995-04-28'),
('Blanche','Kihn','Justice83@gmail.com','{"country": "Montenegro", "state": "Tennessee", "city": "West Jessyburgh"}',1,'1986-04-05'),
('Fleta','Brakus','Gordon.Lueilwitz1@gmail.com','{"country": "Marshall Islands", "state": "Georgia", "city": "East Marques"}',0,'1969-11-03'),
('Myrl','Homenick','Francisca.Goodwin22@gmail.com','{"country": "Ecuador", "state": "Georgia", "city": "Port Annettechester"}',2,'1980-04-06'),
('Judah','Schumm','Major_Heaney96@gmail.com','{"country": "Lithuania", "state": "Washington", "city": "West Jayson"}',2,'1973-05-09'),
('Dessie','Sanford','Gillian_Ortiz24@yahoo.com','{"country": "Cook Islands", "state": "North Dakota", "city": "Adellefort"}',1,'1962-09-19'),
('Karl','Marks','Estella_Lemke47@hotmail.com','{"country": "Albania", "state": "Montana", "city": "Satterfieldburgh"}',0,'1965-01-23'),
('Joanne','Turcotte','Isaias_Nienow@hotmail.com','{"country": "Guatemala", "state": "Virginia", "city": "Celialand"}',1,'1980-03-31');